site:
  title: New Key Features of AAP2.6
  start_page: AAP2.6-New-KeyFeatures::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
